### PR TITLE
client: get verb must use empty body

### PR DESCRIPTION
**Pull request by rodmatos**

### CODE REVIEW

**Review by danopia — APPROVED** [review]
I've definitely performed GET requests previously with this ok. Did this come up in old code (suggesting a Deno change) or are you adding new APIs/code?

**Comment by rodmatos** [comment]
This problem has come up with old code. I have manually edited the cached dependency and the change is functional.

**Comment by danopia** [comment]
It looks like this was one of the API changes in Deno 1.9.1: https://github.com/denoland/deno/commit/9e6cd91014ac4a0d34556b0d09cbe25e4e0930c6

**Pull request merged**
